# This is a basic workflow to help you get started with Actions

name: CI API TEST

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Linux:
    name: Validate API spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 2.4.0
      - name: Lint
        run: inso lint spec spc_02c2aac2a8e04da28500240dcba63854 --ci
      - name: Run test suites
        run: inso run test "Sample Test Suite" --env "OpenAPI env" --ci
      - name: Generate declarative config
        run: inso generate config spc_02c2aac2a8e04da28500240dcba63854 --type declarative --ci
