# This is a basic workflow to help you get started with Actions

name: CI API TEST

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Linux:
    name: Validate API spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 2.4.0
      - name: Lint
        run: inso lint spec spc_0960f423b04645da9205582895e4724a --ci
      - name: Run test suites
        run: inso run test "Sample Test Suite" --env "OpenAPI env" --ci
      - name: Generate declarative config
        run: inso generate config "Pet Store Insomia" --type declarative --ci
